const createPageObject = (city, country) => {
  const pageCatalog = {
    ru: [
      {
        link: "sdat-posutochno-zhile",
        title: `Продажа бронирования отелей и посуточной аренды жилья - ${city}, ${country} | Your Price Booking - лучшие условия для отельеров.`,
        description: `Сдайте жилье посуточно ${city}, ${country} с Your Price Booking и получайте оплату перед заселением. 5% комиссии, гибкие цены, регистрация объектов онлайн. Удовлетворите потребности бронирующих гостей, предлагая индивидуальные цены. Привлекайте путешественников, знающих, что наши комиссии для отельеров минимальны. Регистрируйте отели, квартиры, дома и многое другое сегодня и привлекайте клиентов! Лучшие условия для отельеров онлайн на сервисе бронирования Your Price Booking.`,
      },
      {
        link: "sdat-nomer-v-motele",
        title: `Сдача номера в мотеле с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте номер в вашем мотеле в локации ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой мотель прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
      {
        link: "sdat-nomer-v-capsule-hotel",
        title: `Сдача капсульных номеров с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте свои капсульные номера в Capsule Hotel на ваших условиях с Your Price Booking | ${city}. Получайте оплату до заселения, наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, создавайте акционные предложения безплатно. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте ваш Capsule Hotel прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
      {
        link: "sdat-nomer-v-guest-house",
        title: `Сдача номеров в Guest House с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте номера в вашем Guest House с Your Price Booking  | ${city}, ${country} на ваших условиях. Получайте оплату до заселения. Регистрация займет 2 минуты. Наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой Guest House прямо сейчас, пройдите онлайн-верификацию и начните привлекать новых клиентов.`,
      },
      {
        link: "sdat-komnatu-v-dome-posutochno",
        title: `Сдача комнаты в доме посуточно с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте комнату в вашем доме посуточно — ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте комнату в доме или любой другой объект жилой недвижимости прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
      {
        link: "sdat-komnatu-v-kvartire-posutochno",
        title: `Сдача комнат посуточно | ${city}, ${country} | самый удобный онлайн сервис Your Price Booking`,
        description: `Сдайте комнату в квартире посуточно - ${city}, ${country}, с оплатой перед заселением. Мы взимаем всего 5% комиссии и позволяем вам гибко управлять ценами. Зарегистрируйте свое жилье онлайн и получите клиентов. Предлагайте индивидуальные цены, видимые для ищущих бронирование. Не упустите возможность предложить хорошие цены и получить клиентов с минимальной комиссией. Регистрируйтесь и начните аренду жилья прямо сейчас.`,
      },
      {
        link: "sdat-mesto-v-hostele",
        title: `Гибкие условия аренды мест в хостеле с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте место в вашем хостеле  | ${city}, ${country} — на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия всего 5%. Управляйте ценами по вашему усмотрению и предлагайте индивидуальные предложения для каждого клиента. У вас есть возможность видеть всех пользователей, интересующихся вашими свободными местами, и делать акционные предложения. Путешественники знают, что мы предлагаем отельерам минимальные комиссии, и ожидают от вас выгодные цены. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте ваш хостел на нашем сайте, пройдите онлайн-верификацию и начните продавать через наш сервис.`,
      },
      {
        link: "sdat-nomer-v-otele",
        title: `Гибкие условия сдачи номеров в вашем отеле с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте номер в вашем отеле в городе ${city} на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия всего 5%. Управляйте ценами по вашему усмотрению и предлагайте индивидуальные предложения для каждого клиента. У вас есть возможность видеть всех пользователей, интересующихся вашими свободными номерами, и делать акционные предложения. Путешественники знают, что мы предлагаем отельерам минимальные комиссии, и ожидают от вас выгодные цены. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой отель прямо сейчас, пройдите онлайн-верификацию и начните привлекать новых клиентов.`,
      },
      {
        link: "sdat-nomer-v-gostinitse",
        title: `Гибкий и выгодный способ сдачи номеров в гостинице с Your Price Booking | ${city}, ${country}`,
        description: `Оптимизируйте свой бизнес с помощью Your Price Booking - сервиса бронирования гостиниц и посуточной оренды жилья. У нас вы сдаете номера на ваших условиях, видите всех пользователей, которым подходят ваши предложения, и предлагаете индивидуальные цены конфиденциально. Отельеры платят всего 5% комиссии с каждой сделки и могут менять цены по своему усмотрению. Нет паритета цен - только гибкость и прозрачность. Регистрируйтесь сейчас, проходите верификацию онлайн и привлекайте новых клиентов.`,
      },
      {
        link: "sdat-dom-posutochno",
        title: `Сдать дом посуточно | ${city}. Гибкие условия с Your Price Booking`,
        description: `Сдайте свой дом посуточно | ${city}, Украина. На лучших условиях с Your Price Booking. Получайте оплату до заселения, наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения сколько угодно и безплатно. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой дом, виллу или шале прямо сейчас. Пройдите онлайн-верификацию и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
      {
        link: "sdat-apartamenty-posutochno",
        title: `Сдача апартаментов посуточно ${city} | Your Price Booking`,
        description: `Сдайте апартаменты на суточную аренду в локации ${city}, ${country} на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте апартаменты сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
      {
        link: "sdat-kvartiru-posutochno",
        title: `Сдача квартиры посуточно с Your Price Booking | ${city}, ${country}`,
        description: `Сдайте вашу квартиру на суточную аренду в локации ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте вашу квартиру прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
      },
    ],
    uk: [
      {
        link: "zdati-zhitlo-dobovo",
        title: `Продаж бронювання готелів та добової оренда житла - ${city}, ${country} | Your Price Booking - найкращі умови для готельєрів.`,
        description: `Здавайте житло добово - ${city}, ${country} за допомогою Your Price Booking. Отримуйте оплату перед заселенням. 5% комісії, гнучкі ціни, реєстрація об'єктів онлайн. Задовольняйте потреби бронюючих гостей, запропоновуючи індивідуальні ціни. Привертайте подорожуючих, які знають, що наші комісії для господарів є мінімальними. Реєструйте готелі, квартири, будинки та багато іншого вже сьогодні і приваблюйте клієнтів! Найкращі умови для готельєрів тіки на онлайн сервісі бронювання Your Price Booking.`,
      },
      {
        link: "zdati-nomer-u-moteli",
        title: `Здати номера в мотелі з Your Price Booking | ${city}, ${country}`,
        description: `Здайте номер у вашому мотелі у локації ${city}, на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій мотель прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
      {
        link: "zdati-nomer-v-capsule-hotel",
        title: `Продаж бронювання капсульних номерів через Your Price Booking | ${city}, ${country}`,
        description: `Здайте свої капсули в Capsule Hotel на ваших умовах з Your Price Booking | ${city}. Отримуйте оплату до заселення, наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачите всіх користувачів, створюйте акційні пропозиції безкоштовно. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте ваш Capsule Hotel прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
      {
        link: "zdati-nomer-v-guest-house",
        title: `Продаж бронювання номерів у Guest House з Your Price Booking | ${city}, ${country}`,
        description: `Оренда номерів у Вашому Гостьовому Домі з Your Price Booking | ${city}, ${country} на ваших умовах. Отримайте оплату перед заселенням. Реєстрація займе 2 хвилини. Наша комісія становить лише 5%. Ви маєте повний контроль над цінами та можете конфіденційно пропонувати індивідуальні пропозиції. Переглядайте всіх користувачів, зацікавлених у вашій оренді, і створюйте рекламні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям і очікуємо від вас чудових цін. У нас немає принципу паритету цін, лише гнучкість і прозорість. Зареєструйте свій Гостьовий будинок прямо зараз, пройдіть онлайн-верифікацію та починайте залучати нових клієнтів.`,
      },
      {
        link: "zdati-kimnatu-v-budinku-dobovo",
        title: `Здати в оренду кімнату в будинку подобово з Your Price Booking | ${city}, ${country}`,
        description: `Здайте мандрівникам кімнату у своєму будинку подобово – ${city}, на ваших умовах за вашою ціною бронювання. Отримайте оплату до заселення і наша комісія складає всього 5%. Ви маєте повний контроль над цінами та можете конфіденційно пропонувати персоналізовані пропозиції. Переглядайте всіх користувачів, зацікавлених у вашій оренді, та створюйте рекламні пропозиції безкоштовно та без обмежень. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікуємо від вас відмінних цін. У нас немає принципу паритету цін, є лише гнучкість та прозорість. Зареєструйте кімнату у своєму будинку або іншому житловому об'єкті прямо зараз, пройдіть онлайн-перевірку та почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
      {
        link: "zdati-kimnatu-dobovo",
        title: `Продаж бронювання кімнат подобово | ${city}, ${country} | найзручніший онлайн сервіс Your Price Booking`,
        description: `Здайте кімнату в квартирі добово - ${city}, ${country}, з оплатою перед заселенням. Ми беремо лише 5% комісії та надаємо можливість гнучкого керування цінами. Зареєструйте своє житло онлайн та отримайте клієнтів. Пропонуйте індивідуальні ціни, видимі для тих, хто шукає бронювання. Не пропустіть можливість запропонувати хороші ціни та отримати клієнтів з мінімальною комісією. Реєструйтеся і почніть здачу житла прямо зараз.`,
      },
      {
        link: "zdati-mistse-u-hosteli",
        title: `Гнучкі умови оренди місць у хостелі з Your Price Booking | ${city}, ${country}`,
        description: `Здайте місце у вашому хостелі ${city}, ${country} — на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, а наша комісія лише 5%. Керуйте цінами на ваш розсуд і пропонуйте індивідуальні пропозиції для кожного клієнта. Ви можете бачити всіх користувачів, які цікавляться вашими вільними місцями, і робити акційні пропозиції. Мандрівники знають, що ми пропонуємо готельєрам мінімальні комісії, і очікують від вас вигідні ціни. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте ваш хостел на нашому сайті, пройдіть онлайн-верифікацію та почніть продавати через наш сервіс.`,
      },
      {
        link: "zdati-nomer-u-goteli",
        title: `Гнучкі умови здачі номерів у вашому готелі Your Price Booking | ${city}, ${country}`,
        description: `Здайте номер у вашому готелі на ваших умовах із Your Price Booking | ${city}. Отримуйте оплату до заселення, а наша комісія лише 5%. Керуйте цінами на ваш розсуд і пропонуйте індивідуальні пропозиції для кожного клієнта. Ви можете бачити всіх користувачів, які цікавляться вашими вільними номерами, і робити акційні пропозиції. Мандрівники знають, що ми пропонуємо готельєрам мінімальні комісії, і очікують від вас вигідні ціни. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій готель зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів.`,
      },
      {
        link: "zdati-nomer-v-goteli-vsih-tipiv",
        title: `Гнучкий та вигідний спосіб здачі номерів у готелях всіх типів Your Price Booking | ${city}, ${country}`,
        description: `Оптимізуйте свій бізнес за допомогою Your Price Booking – сервісу бронювання готелів усіх типів тадобової оренди житла. У нас ви здаєте номери на ваших умовах, бачите всіх користувачів, яким підходять ваші пропозиції, та пропонуєте індивідуальні ціни конфіденційно. Готельєри платять лише 5% комісії з кожної угоди і можуть змінювати ціни на власний розсуд. Немає паритету цін – лише гнучкість та прозорість. Реєструйтеся зараз, проходьте верифікацію онлайн та залучайте нових клієнтів.`,
      },
      {
        link: "zdati-budinok-dobovo",
        title: `Здати в оренду будинок подобово | ${city}. Гнучкі умови з Your Price Booking`,
        description: `Здати свій будинок добово ${city}, ${country}. На кращих умовах із Your Price Booking. Отримуйте оплату до заселення, наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачите всіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції скільки завгодно та безкоштовно. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій будинок, віллу або шале прямо зараз. Пройдіть онлайн-верифікацію та почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
      {
        link: "zdati-apartamenti-dobovo",
        title: `Сдача в оренду апартаментів добово ${city} | Your Price Booking`,
        description: `Здайте апартаменти на добову оренду у локації ${city}, ${country} на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте апартаменти зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
      {
        link: "zdati-kvartiru-dobovo",
        title: `Здати в аренду квартиру добово через Your Price Booking | ${city}, ${country}`,
        description: `Здайте квартиру на добову оренду в локації ${city}, на ваших умовах з Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте вашу квартиру прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
      },
    ],
    en: [
      {
        link: "rent-out-housing-daily",
        title: `Sales, hotel reservations and daily rental housing - ${city}, ${country} | Your Price Booking - the best conditions for hoteliers.`,
        description: `Rent accommodation to tourists per day | ${city}, ${country}e. Get paid before registering. 5% commission, flexible prices, real estate registration online. Satisfy guests' booking needs by offering customized pricing. Attract travelers who know our host commissions are minimal. List hotels, apartments, houses, etc. today and attract customers! The best conditions for hoteliers on the online reservation service Your Price Booking.`,
      },
      {
        link: "rent-a-motel-room",
        title: `Book motel rooms with Your Price Booking | ${city}, ${country}`,
        description: `Rent out your hotel room on your terms with Your Price Booking | ${city}. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your available numbers and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hotel right now, go through online verification and start attracting new clients.`,
      },
      {
        link: "rent-a-room-in-capsule-hotel",
        title: `Selling capsule room bookings through Your Price Booking | ${city}, ${country}`,
        description: `Rent out your capsule rooms at Capsule Hotel on your terms with Your Price Booking | ${city}. Receive payment before moving in, our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users, create promotional offers for free. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your Capsule Hotel right now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
      },
      {
        link: "rent-a-room-in-guest-house",
        title: `Sale of guest house room reservations with Your Price Booking | ${city}, ${country}`,
        description: `Rent out rooms in your Guest House with Your Price Booking | ${city}, ${country} on your terms. Receive payment before moving in. Registration will take 2 minutes. Our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your Guest House right now, go through online verification and start attracting new clients.`,
      },
      {
        link: "rent-a-room-in-a-house-daily",
        title: `Rent a room on a daily basis with Your Price Booking | ${city}, ${country}`,
        description: `Rent a room in your house to travelers daily - ${city}, on your terms at your booking price. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can privately offer personalized offers. View all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register a room in your home or other residential property now, complete the online verification process and start attracting new clients. Registration will only take 2 minutes.`,
      },
      {
        link: "rent-a-room-in-a-flat-daily",
        title: `Sale of daily room reservations | ${city}, ${country} | the most convenient online service Your Price Booking`,
        description: `Rent a room in an apartment daily in the city of ${city}, ${country}, with payment before check-in. We charge only 5% commission and provide flexible price management. Register your accommodation online and get customers. Offer custom pricing visible to those looking for a reservation. Do not miss the opportunity to offer good prices and get customers with minimal commission. Register and start renting out your home right now.`,
      },
      {
        link: "rent-a-place-in-a-hostel",
        title: `Flexible conditions for renting hostel beds with Your Price Booking | ${city}, ${country}`,
        description: `Rent out a place in your hostel | ${city}, ${country} — on your terms with Your Price Booking. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your free places and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hostel on our website, go through online verification and start selling through our service.`,
      },
      {
        link: "rent-a-hotel-room-daily",
        title: `Flexible conditions for renting rooms in your hotel with Your Price Booking | ${city}, ${country}`,
        description: `Rent out your hotel room on your terms with Your Price Booking | ${city}. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your available numbers and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hotel right now, go through online verification and start attracting new clients.`,
      },
      {
        link: "rent-a-hotel-room-in-hotel-of-all-types",
        title: `A flexible and profitable way to rent out rooms in hotels of all types with Your Price Booking | ${city}, ${country}`,
        description: `Optimize your business with Your Price Booking - a service for booking hotels of all types and daily rental housing. With us, you rent out rooms on your terms, see all the users who are eligible for your offers, and offer individual, confidential prices. Hoteliers pay only 5% commission on each transaction and can change prices at their discretion. There is no price parity - only flexibility and transparency. Register now, go through online verification and attract new clients.`,
      },
      {
        link: "rent-a-house-daily",
        title: `Rent a house by the day | ${city}. Flexible conditions with Your Price Booking`,
        description: `Rent your house daily | ${city}, ${country}. On better terms with Your Price Booking. Get paid before you move in, our commission is only 5%. You have complete control over prices and you can make individual offers confidentially. See all users interested in your rental and create promotional offers as much as you want and for free. Travelers know that we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your house, villa or chalet right now. Get verified online and start attracting new customers. Registration will take only 2 minutes.`,
      },
      {
        link: "rent-an-apartment-daily",
        title: `Apartments for rent by the day ${city} | Your Price Booking`,
        description: `Rent out apartments for daily rent in ${city}, ${country} on your terms with Your Price Booking. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your apartment now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
      },
      {
        link: "rent-a-flat-daily",
        title: `Rent an apartment to tourists for a day through Your Price Booking | ${city}, ${country}`,
        description: `Rent out your apartment for daily rent in the ${city} location, on your terms with Your Price Booking. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your apartment right now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
      },
    ],
    pl: [
      {
        link: "wynajme-mieszkanie",
        title: `Sprzedaż, rezerwacje hoteli i dobowy wynajem mieszkań - ${city}, ${country} | Your Price Booking - najlepsze warunki dla hotelarzy.`,
        description: `Wynajmij apartamenty na dzień - ${city}, ${country} z Your Price Booking i zarabiaj przed wprowadzeniem się. 5% prowizji, elastyczne ceny, rejestracja obiektu online. Spełniaj potrzeby rezerwacyjne swoich gości, oferując spersonalizowane ceny. Przyciągaj podróżnych, którzy wiedzą, że opłaty naszych właścicieli są minimalne. Wystaw hotele, apartamenty, domy i nie tylko już dziś i przyciągnij klientów! Najlepsze warunki dla hotelarzy w serwisie rezerwacji online Your Price Booking.`,
      },
      {
        link: "wynajme-pokoj-w-motelu",
        title: `Zarezerwuj pokoje motelowe z Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij pokój w swoim motelu w lokalizacji ${city}, na swoich warunkach z Your Price Booking. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój motel już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
      {
        link: "wynajme-pokoj-w-hotelu-kapsulowym",
        title: `Sprzedaż rezerwacji pokoi kapsułowych za pośrednictwem Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij pokoje kapsułowe w Capsule Hotel na swoich warunkach z Your Price Booking | ${city}. Otrzymaj płatność przed wprowadzeniem się, nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników, twórz oferty promocyjne za darmo. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój Hotel Kapsułowy już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
      {
        link: "wynajme-pokoj-w-domu-gosccinnym",
        title: `Sprzedaż rezerwacji pokoi w pensjonacie z Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij pokoje w swoim pensjonacie z Your Price Booking | ${city}, ${country} na Twoich warunkach. Otrzymaj płatność przed wprowadzeniem się. Rejestracja zajmie 2 minuty. Nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój Pensjonat już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów.`,
      },
      {
        link: "wynajme-pokoj-w-domu",
        title: `Wynajmij pokój w swoim domu na dobę z Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij pokój w swoim domu podróżującym codziennie - ${city}, na Twoich warunkach i za cenę rezerwacji. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz prywatnie oferować spersonalizowane oferty. Przeglądaj wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj pokój w swoim domu lub innej nieruchomości mieszkalnej już teraz, przejdź proces weryfikacji online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
      {
        link: "wynajme-pokoj-w-mieszkaniu",
        title: `Sprzedaż dziennych rezerwacji pokoi | ${city}, ${country} | najwygodniejsza usługa online Twoja cena Rezerwacja`,
        description: `Wynajmij pokój w mieszkaniu na dobę w mieście ${city}, ${country}, z płatnością przed zameldowaniem. Pobieramy tylko 5% prowizji i zapewniamy elastyczne zarządzanie cenami. Zarejestruj swoje zakwaterowanie online i zdobywaj klientów. Oferuj niestandardowe ceny widoczne dla osób poszukujących rezerwacji. Nie przegap okazji, aby zaoferować dobre ceny i pozyskać klientów przy minimalnej prowizji. Zarejestruj się i zacznij wynajmować swój dom już teraz.`,
      },
      {
        link: "wynajme-miejsce-w-hostelu",
        title: `Elastyczne warunki wynajmu łóżek hostelowych z Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij miejsce w swoim hostelu | ${city}, ${country} — na Twoich warunkach dzięki Your Price Booking. Otrzymuj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Zarządzaj cenami według własnego uznania i oferuj spersonalizowane oferty dla każdego klienta. Masz możliwość zobaczenia wszystkich użytkowników zainteresowanych Twoimi wolnymi miejscami i przedstawienia ofert promocyjnych. Podróżni wiedzą, że oferujemy hotelarzom minimalne prowizje i oczekujemy od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój hostel na naszej stronie internetowej, przejdź weryfikację online i rozpocznij sprzedaż za pośrednictwem naszego serwisu.`,
      },
      {
        link: "wynajmij-pokoj-w-hotelu",
        title: `Elastyczne warunki wynajmu pokoi w Twoim hotelu dzięki Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij swój pokój hotelowy na swoich warunkach dzięki opcji Your Price Booking | ${city}. Otrzymuj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Zarządzaj cenami według własnego uznania i oferuj spersonalizowane oferty dla każdego klienta. Masz możliwość zobaczenia wszystkich użytkowników zainteresowanych Twoimi dostępnymi numerami i przedstawienia ofert promocyjnych. Podróżni wiedzą, że oferujemy hotelarzom minimalne prowizje i oczekujemy od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój hotel już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów.`,
      },
      {
        link: "wynajac-w-hotelach-wszystkich-typow",
        title: `Elastyczny i opłacalny sposób wynajmu pokoi we wszelkiego rodzaju hotelach dzięki Your Price Booking | ${city}, ${country}`,
        description: `Zoptymalizuj swój biznes dzięki Your Price Booking - usłudze rezerwacji hoteli wszystkich typów i mieszkań na dobowy wynajem. Z nami wynajmujesz pokoje na swoich warunkach, widzisz wszystkich użytkowników, którzy mogą skorzystać z Twoich ofert i oferujesz indywidualne, poufne ceny. Hotelarze płacą tylko 5% prowizji od każdej transakcji i mogą zmieniać ceny według własnego uznania. Nie ma parytetu cenowego – jest tylko elastyczność i przejrzystość. Zarejestruj się już teraz, przejdź weryfikację online i zdobądź nowych klientów.`,
      },
      {
        link: "wynajac-dom",
        title: `Wynajmij dom na doby | ${city}. Elastyczne warunki z Your Price Booking`,
        description: `Wynajmij swój dom codziennie ${city}, ${country}. Lepsze warunki dzięki Twojej cenie rezerwacji. Zarabiaj zanim się wprowadzisz, nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz poufnie składać indywidualne oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim najmem i twórz oferty promocyjne, ile chcesz i za darmo. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój dom, willę lub domek już teraz. Zweryfikuj się online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
      {
        link: "wynajem-mieszkan-do-wynajecia",
        title: `Mieszkania do wynajęcia na dzień ${city} | Your Price Booking`,
        description: `Wynajmij apartamenty do codziennego wynajęcia ${city}, ${country} na Twoich warunkach dzięki Your Price Booking. Zarabiaj zanim się wprowadzisz, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz poufnie składać indywidualne oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj apartamenty już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
      {
        link: "wynajac-mieszkanie",
        title: `Wynajmij mieszkanie turystom na jeden dzień poprzez Your Price Booking | ${city}, ${country}`,
        description: `Wynajmij swoje mieszkanie na dobowy wynajem w lokalizacji ${city}, na Twoich warunkach z Your Price Booking. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swoje mieszkanie już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
      },
    ],
  };

  return pageCatalog;
};
module.exports = createPageObject;

// const title = {
//   ru: [
//     `Продажа бронирования отелей и посуточной аренды жилья - ${city}, ${country} | Your Price Booking - лучшие условия для отельеров.`,
//     `Сдача номера в мотеле с Your Price Booking | ${city}, ${country}`,
//     `Сдача капсульных номеров с Your Price Booking | ${city}, ${country}`,
//     `Сдача номеров в Guest House с Your Price Booking | ${city}, ${country}`,
//     `Сдача комнаты в доме посуточно с Your Price Booking | ${city}, ${country}`,
//     `Сдача комнат посуточно | ${city}, ${country} | самый удобный онлайн сервис Your Price Booking`,
//     `Гибкие условия аренды мест в хостеле с Your Price Booking | ${city}, ${country}`,
//     `Гибкие условия сдачи номеров в вашем отеле с Your Price Booking | ${city}, ${country}`,
//     `Гибкий и выгодный способ сдачи номеров в гостинице с Your Price Booking | ${city}, ${country}`,
//     `Сдать дом посуточно | ${city}. Гибкие условия с Your Price Booking`,
//     `Сдача апартаментов посуточно ${city} | Your Price Booking`,
//     `Сдача квартиры посуточно с Your Price Booking | ${city}, ${country}`,
//   ],
//   uk: [
//     `Продаж бронювання готелів та добової оренда житла - ${city}, ${country} | Your Price Booking - найкращі умови для готельєрів.`,
//     `Здати номера в мотелі з Your Price Booking | ${city}, ${country}`,
//     `Продаж бронювання капсульних номерів через Your Price Booking | ${city}, ${country}`,
//     `Продаж бронювання номерів у Guest House з Your Price Booking | ${city}, ${country}`,
//     `Здати в оренду кімнату в будинку подобово з Your Price Booking | ${city}, ${country}`,
//     `Продаж бронювання кімнат подобово | ${city}, ${country} | найзручніший онлайн сервіс Your Price Booking`,
//     `Гнучкі умови оренди місць у хостелі з Your Price Booking | ${city}, ${country}`,
//     `Гнучкі умови здачі номерів у вашому готелі Your Price Booking | ${city}, ${country}`,
//     `Гнучкий та вигідний спосіб здачі номерів у готелях всіх типів Your Price Booking | ${city}, ${country}`,
//     `Здати в оренду будинок подобово | ${city}. Гнучкі умови з Your Price Booking`,
//     `Сдача в оренду апартаментів добово ${city} | Your Price Booking`,
//     `Здати в аренду квартиру добово через Your Price Booking | ${city}, ${country}`,
//   ],
//   pl: [
//     `Sprzedaż, rezerwacje hoteli i dobowy wynajem mieszkań - ${city}, ${country} | Your Price Booking - najlepsze warunki dla hotelarzy.`,
//     `Zarezerwuj pokoje motelowe z Your Price Booking | ${city}, ${country}`,
//     `Sprzedaż rezerwacji pokoi kapsułowych za pośrednictwem Your Price Booking | ${city}, ${country}`,
//     `Sprzedaż rezerwacji pokoi w pensjonacie z Your Price Booking | ${city}, ${country}`,
//     `Wynajmij pokój w swoim domu na dobę z Your Price Booking | ${city}, ${country}`,
//     `Sprzedaż dziennych rezerwacji pokoi | ${city}, ${country} | najwygodniejsza usługa online Twoja cena Rezerwacja`,
//     `Elastyczne warunki wynajmu łóżek hostelowych z Your Price Booking | ${city}, ${country}`,
//     `Elastyczne warunki wynajmu pokoi w Twoim hotelu dzięki Your Price Booking | ${city}, ${country}`,
//     `Elastyczny i opłacalny sposób wynajmu pokoi we wszelkiego rodzaju hotelach dzięki Your Price Booking | ${city}, ${country}`,
//     `Wynajmij dom na doby | ${city}. Elastyczne warunki z Your Price Booking`,
//     `Mieszkania do wynajęcia na dzień ${city} | Your Price Booking`,
//     `Wynajmij mieszkanie turystom na jeden dzień poprzez Your Price Booking | ${city}, ${country}`,
//   ],
//   en: [
//     `Sales, hotel reservations and daily rental housing - ${city}, ${country} | Your Price Booking - the best conditions for hoteliers.`,
//     `Book motel rooms with Your Price Booking | ${city}, ${country}`,
//     `Selling capsule room bookings through Your Price Booking | ${city}, ${country}`,
//     `Sale of guest house room reservations with Your Price Booking | ${city}, ${country}`,
//     `Rent a room on a daily basis with Your Price Booking | ${city}, ${country}`,
//     `Sale of daily room reservations | ${city}, ${country} | the most convenient online service Your Price Booking`,
//     `Flexible conditions for renting hostel beds with Your Price Booking | ${city}, ${country}`,
//     `Flexible conditions for renting rooms in your hotel with Your Price Booking | ${city}, ${country}`,
//     `A flexible and profitable way to rent out rooms in hotels of all types with Your Price Booking | ${city}, ${country}`,
//     `Rent a house by the day | ${city}. Flexible conditions with Your Price Booking`,
//     `Apartments for rent by the day ${city} | Your Price Booking`,
//     `Rent an apartment to tourists for a day through Your Price Booking | ${city}, ${country}`,
//   ],
// };

// const description = {
//   ru: [
//     `Сдайте жилье посуточно ${city}, ${country} с Your Price Booking и получайте оплату перед заселением. 5% комиссии, гибкие цены, регистрация объектов онлайн. Удовлетворите потребности бронирующих гостей, предлагая индивидуальные цены. Привлекайте путешественников, знающих, что наши комиссии для отельеров минимальны. Регистрируйте отели, квартиры, дома и многое другое сегодня и привлекайте клиентов! Лучшие условия для отельеров онлайн на сервисе бронирования Your Price Booking.`,
//     `Сдайте номер в вашем мотеле в локации ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой мотель прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//     `Сдайте свои капсульные номера в Capsule Hotel на ваших условиях с Your Price Booking | ${city}. Получайте оплату до заселения, наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, создавайте акционные предложения безплатно. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте ваш Capsule Hotel прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//     `Сдайте номера в вашем Guest House с Your Price Booking  | ${city}, ${country} на ваших условиях. Получайте оплату до заселения. Регистрация займет 2 минуты. Наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой Guest House прямо сейчас, пройдите онлайн-верификацию и начните привлекать новых клиентов.`,
//     `Сдайте комнату в вашем доме посуточно — ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте комнату в доме или любой другой объект жилой недвижимости прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//     `Сдайте комнату в квартире посуточно - ${city}, ${country}, с оплатой перед заселением. Мы взимаем всего 5% комиссии и позволяем вам гибко управлять ценами. Зарегистрируйте свое жилье онлайн и получите клиентов. Предлагайте индивидуальные цены, видимые для ищущих бронирование. Не упустите возможность предложить хорошие цены и получить клиентов с минимальной комиссией. Регистрируйтесь и начните аренду жилья прямо сейчас.`,
//     `Сдайте место в вашем хостеле  | ${city}, ${country} — на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия всего 5%. Управляйте ценами по вашему усмотрению и предлагайте индивидуальные предложения для каждого клиента. У вас есть возможность видеть всех пользователей, интересующихся вашими свободными местами, и делать акционные предложения. Путешественники знают, что мы предлагаем отельерам минимальные комиссии, и ожидают от вас выгодные цены. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте ваш хостел на нашем сайте, пройдите онлайн-верификацию и начните продавать через наш сервис.`,
//     `Сдайте номер в вашем отеле в городе ${city} на ваших условиях с Your Price Booking. Получайте оплату до заселения, а наша комиссия всего 5%. Управляйте ценами по вашему усмотрению и предлагайте индивидуальные предложения для каждого клиента. У вас есть возможность видеть всех пользователей, интересующихся вашими свободными номерами, и делать акционные предложения. Путешественники знают, что мы предлагаем отельерам минимальные комиссии, и ожидают от вас выгодные цены. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой отель прямо сейчас, пройдите онлайн-верификацию и начните привлекать новых клиентов.`,
//     `Оптимизируйте свой бизнес с помощью Your Price Booking - сервиса бронирования гостиниц и посуточной оренды жилья. У нас вы сдаете номера на ваших условиях, видите всех пользователей, которым подходят ваши предложения, и предлагаете индивидуальные цены конфиденциально. Отельеры платят всего 5% комиссии с каждой сделки и могут менять цены по своему усмотрению. Нет паритета цен - только гибкость и прозрачность. Регистрируйтесь сейчас, проходите верификацию онлайн и привлекайте новых клиентов.`,
//     `Сдайте свой дом посуточно | ${city}, Украина. На лучших условиях с Your Price Booking. Получайте оплату до заселения, наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения сколько угодно и безплатно. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте свой дом, виллу или шале прямо сейчас. Пройдите онлайн-верификацию и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//     `Сдайте апартаменты на суточную аренду в локации ${city}, ${country} на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте апартаменты сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//     `Сдайте вашу квартиру на суточную аренду в локации ${city}, на ваших условиях с Your Price Booking. Получайте оплату до заселения, и наша комиссия составляет всего 5%. У вас есть полный контроль над ценами, и вы можете предлагать индивидуальные предложения конфиденциально. Видите всех пользователей, заинтересованных в вашей аренде, и создавайте акционные предложения. Путешественники знают, что мы предлагаем минимальные комиссии отелям и ожидают от вас выгодных цен. У нас нет принципа паритета цен, только гибкость и прозрачность. Зарегистрируйте вашу квартиру прямо сейчас, пройдите онлайн-верификацию, и начните привлекать новых клиентов. Регистрация займет всего 2 минуты.`,
//   ],
//   uk: [
//     `Здавайте житло добово - ${city}, ${country} за допомогою Your Price Booking. Отримуйте оплату перед заселенням. 5% комісії, гнучкі ціни, реєстрація об'єктів онлайн. Задовольняйте потреби бронюючих гостей, запропоновуючи індивідуальні ціни. Привертайте подорожуючих, які знають, що наші комісії для господарів є мінімальними. Реєструйте готелі, квартири, будинки та багато іншого вже сьогодні і приваблюйте клієнтів! Найкращі умови для готельєрів тіки на онлайн сервісі бронювання Your Price Booking.`,
//     `Здайте номер у вашому мотелі у локації ${city}, на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій мотель прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//     `Здайте свої капсули в Capsule Hotel на ваших умовах з Your Price Booking | ${city}. Отримуйте оплату до заселення, наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачите всіх користувачів, створюйте акційні пропозиції безкоштовно. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте ваш Capsule Hotel прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//     `Оренда номерів у Вашому Гостьовому Домі з Your Price Booking | ${city}, ${country} на ваших умовах. Отримайте оплату перед заселенням. Реєстрація займе 2 хвилини. Наша комісія становить лише 5%. Ви маєте повний контроль над цінами та можете конфіденційно пропонувати індивідуальні пропозиції. Переглядайте всіх користувачів, зацікавлених у вашій оренді, і створюйте рекламні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям і очікуємо від вас чудових цін. У нас немає принципу паритету цін, лише гнучкість і прозорість. Зареєструйте свій Гостьовий будинок прямо зараз, пройдіть онлайн-верифікацію та починайте залучати нових клієнтів.`,
//     `Здайте мандрівникам кімнату у своєму будинку подобово – ${city}, на ваших умовах за вашою ціною бронювання. Отримайте оплату до заселення і наша комісія складає всього 5%. Ви маєте повний контроль над цінами та можете конфіденційно пропонувати персоналізовані пропозиції. Переглядайте всіх користувачів, зацікавлених у вашій оренді, та створюйте рекламні пропозиції безкоштовно та без обмежень. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікуємо від вас відмінних цін. У нас немає принципу паритету цін, є лише гнучкість та прозорість. Зареєструйте кімнату у своєму будинку або іншому житловому об'єкті прямо зараз, пройдіть онлайн-перевірку та почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//     `Здайте кімнату в квартирі добово - ${city}, ${country}, з оплатою перед заселенням. Ми беремо лише 5% комісії та надаємо можливість гнучкого керування цінами. Зареєструйте своє житло онлайн та отримайте клієнтів. Пропонуйте індивідуальні ціни, видимі для тих, хто шукає бронювання. Не пропустіть можливість запропонувати хороші ціни та отримати клієнтів з мінімальною комісією. Реєструйтеся і почніть здачу житла прямо зараз.`,
//     `Здайте місце у вашому хостелі ${city}, ${country} — на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, а наша комісія лише 5%. Керуйте цінами на ваш розсуд і пропонуйте індивідуальні пропозиції для кожного клієнта. Ви можете бачити всіх користувачів, які цікавляться вашими вільними місцями, і робити акційні пропозиції. Мандрівники знають, що ми пропонуємо готельєрам мінімальні комісії, і очікують від вас вигідні ціни. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте ваш хостел на нашому сайті, пройдіть онлайн-верифікацію та почніть продавати через наш сервіс.`,
//     `Здайте номер у вашому готелі на ваших умовах із Your Price Booking | ${city}. Отримуйте оплату до заселення, а наша комісія лише 5%. Керуйте цінами на ваш розсуд і пропонуйте індивідуальні пропозиції для кожного клієнта. Ви можете бачити всіх користувачів, які цікавляться вашими вільними номерами, і робити акційні пропозиції. Мандрівники знають, що ми пропонуємо готельєрам мінімальні комісії, і очікують від вас вигідні ціни. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій готель зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів.`,
//     `Оптимізуйте свій бізнес за допомогою Your Price Booking – сервісу бронювання готелів усіх типів тадобової оренди житла. У нас ви здаєте номери на ваших умовах, бачите всіх користувачів, яким підходять ваші пропозиції, та пропонуєте індивідуальні ціни конфіденційно. Готельєри платять лише 5% комісії з кожної угоди і можуть змінювати ціни на власний розсуд. Немає паритету цін – лише гнучкість та прозорість. Реєструйтеся зараз, проходьте верифікацію онлайн та залучайте нових клієнтів.`,
//     `Здати свій будинок добово ${city}, ${country}. На кращих умовах із Your Price Booking. Отримуйте оплату до заселення, наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачите всіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції скільки завгодно та безкоштовно. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте свій будинок, віллу або шале прямо зараз. Пройдіть онлайн-верифікацію та почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//     `Здайте апартаменти на добову оренду у локації ${city}, ${country} на ваших умовах із Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте апартаменти зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//     `Здайте квартиру на добову оренду в локації ${city}, на ваших умовах з Your Price Booking. Отримуйте оплату до заселення, і наша комісія складає лише 5%. Ви маєте повний контроль над цінами, і ви можете пропонувати індивідуальні пропозиції конфіденційно. Бачіть усіх користувачів, зацікавлених у вашій оренді, та створюйте акційні пропозиції. Мандрівники знають, що ми пропонуємо мінімальні комісії готелям та очікують від вас вигідних цін. У нас немає принципу паритету цін, лише гнучкість та прозорість. Зареєструйте вашу квартиру прямо зараз, пройдіть онлайн-верифікацію і почніть залучати нових клієнтів. Реєстрація займе лише 2 хвилини.`,
//   ],
//   pl: [
//     `Wynajmij apartamenty na dzień - ${city}, ${country} z Your Price Booking i zarabiaj przed wprowadzeniem się. 5% prowizji, elastyczne ceny, rejestracja obiektu online. Spełniaj potrzeby rezerwacyjne swoich gości, oferując spersonalizowane ceny. Przyciągaj podróżnych, którzy wiedzą, że opłaty naszych właścicieli są minimalne. Wystaw hotele, apartamenty, domy i nie tylko już dziś i przyciągnij klientów! Najlepsze warunki dla hotelarzy w serwisie rezerwacji online Your Price Booking.`,
//     `Wynajmij pokój w swoim motelu w lokalizacji ${city}, na swoich warunkach z Your Price Booking. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój motel już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//     `Wynajmij pokoje kapsułowe w Capsule Hotel na swoich warunkach z Your Price Booking | ${city}. Otrzymaj płatność przed wprowadzeniem się, nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników, twórz oferty promocyjne za darmo. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój Hotel Kapsułowy już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//     `Wynajmij pokoje w swoim pensjonacie z Your Price Booking | ${city}, ${country} na Twoich warunkach. Otrzymaj płatność przed wprowadzeniem się. Rejestracja zajmie 2 minuty. Nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój Pensjonat już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów.`,
//     `Wynajmij pokój w swoim domu podróżującym codziennie - ${city}, na Twoich warunkach i za cenę rezerwacji. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz prywatnie oferować spersonalizowane oferty. Przeglądaj wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj pokój w swoim domu lub innej nieruchomości mieszkalnej już teraz, przejdź proces weryfikacji online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//     `Wynajmij pokój w mieszkaniu na dobę w mieście ${city}, ${country}, z płatnością przed zameldowaniem. Pobieramy tylko 5% prowizji i zapewniamy elastyczne zarządzanie cenami. Zarejestruj swoje zakwaterowanie online i zdobywaj klientów. Oferuj niestandardowe ceny widoczne dla osób poszukujących rezerwacji. Nie przegap okazji, aby zaoferować dobre ceny i pozyskać klientów przy minimalnej prowizji. Zarejestruj się i zacznij wynajmować swój dom już teraz.`,
//     `Wynajmij miejsce w swoim hostelu | ${city}, ${country} — na Twoich warunkach dzięki Your Price Booking. Otrzymuj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Zarządzaj cenami według własnego uznania i oferuj spersonalizowane oferty dla każdego klienta. Masz możliwość zobaczenia wszystkich użytkowników zainteresowanych Twoimi wolnymi miejscami i przedstawienia ofert promocyjnych. Podróżni wiedzą, że oferujemy hotelarzom minimalne prowizje i oczekujemy od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój hostel na naszej stronie internetowej, przejdź weryfikację online i rozpocznij sprzedaż za pośrednictwem naszego serwisu.`,
//     `Wynajmij swój pokój hotelowy na swoich warunkach dzięki opcji Your Price Booking | ${city}. Otrzymuj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Zarządzaj cenami według własnego uznania i oferuj spersonalizowane oferty dla każdego klienta. Masz możliwość zobaczenia wszystkich użytkowników zainteresowanych Twoimi dostępnymi numerami i przedstawienia ofert promocyjnych. Podróżni wiedzą, że oferujemy hotelarzom minimalne prowizje i oczekujemy od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój hotel już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów.`,
//     `Zoptymalizuj swój biznes dzięki Your Price Booking - usłudze rezerwacji hoteli wszystkich typów i mieszkań na dobowy wynajem. Z nami wynajmujesz pokoje na swoich warunkach, widzisz wszystkich użytkowników, którzy mogą skorzystać z Twoich ofert i oferujesz indywidualne, poufne ceny. Hotelarze płacą tylko 5% prowizji od każdej transakcji i mogą zmieniać ceny według własnego uznania. Nie ma parytetu cenowego – jest tylko elastyczność i przejrzystość. Zarejestruj się już teraz, przejdź weryfikację online i zdobądź nowych klientów.`,
//     `Wynajmij swój dom codziennie ${city}, ${country}. Lepsze warunki dzięki Twojej cenie rezerwacji. Zarabiaj zanim się wprowadzisz, nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz poufnie składać indywidualne oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim najmem i twórz oferty promocyjne, ile chcesz i za darmo. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swój dom, willę lub domek już teraz. Zweryfikuj się online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//     `Wynajmij apartamenty do codziennego wynajęcia ${city}, ${country} na Twoich warunkach dzięki Your Price Booking. Zarabiaj zanim się wprowadzisz, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz poufnie składać indywidualne oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj apartamenty już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//     `Wynajmij swoje mieszkanie na dobowy wynajem w lokalizacji ${city}, na Twoich warunkach z Your Price Booking. Otrzymaj płatność przed wprowadzeniem się, a nasza prowizja wynosi tylko 5%. Masz pełną kontrolę nad cenami i możesz z zachowaniem poufności oferować spersonalizowane oferty. Zobacz wszystkich użytkowników zainteresowanych Twoim wynajmem i twórz oferty promocyjne. Podróżni wiedzą, że oferujemy hotelom minimalne prowizje i oczekują od Ciebie świetnych cen. Nie mamy zasady parytetu cen, tylko elastyczność i przejrzystość. Zarejestruj swoje mieszkanie już teraz, przejdź weryfikację online i zacznij pozyskiwać nowych klientów. Rejestracja zajmie tylko 2 minuty.`,
//   ],
//   en: [
//     `Rent accommodation to tourists per day | ${city}, ${country}e. Get paid before registering. 5% commission, flexible prices, real estate registration online. Satisfy guests' booking needs by offering customized pricing. Attract travelers who know our host commissions are minimal. List hotels, apartments, houses, etc. today and attract customers! The best conditions for hoteliers on the online reservation service Your Price Booking.`,
//     `Rent out your hotel room on your terms with Your Price Booking | ${city}. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your available numbers and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hotel right now, go through online verification and start attracting new clients.`,
//     `Rent out your capsule rooms at Capsule Hotel on your terms with Your Price Booking | ${city}. Receive payment before moving in, our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users, create promotional offers for free. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your Capsule Hotel right now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
//     `Rent out rooms in your Guest House with Your Price Booking | ${city}, ${country} on your terms. Receive payment before moving in. Registration will take 2 minutes. Our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your Guest House right now, go through online verification and start attracting new clients.`,
//     `Rent a room in your house to travelers daily - ${city}, on your terms at your booking price. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can privately offer personalized offers. View all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register a room in your home or other residential property now, complete the online verification process and start attracting new clients. Registration will only take 2 minutes.`,
//     `Rent a room in an apartment daily in the city of ${city}, ${country}, with payment before check-in. We charge only 5% commission and provide flexible price management. Register your accommodation online and get customers. Offer custom pricing visible to those looking for a reservation. Do not miss the opportunity to offer good prices and get customers with minimal commission. Register and start renting out your home right now.`,
//     `Rent out a place in your hostel | ${city}, ${country} — on your terms with Your Price Booking. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your free places and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hostel on our website, go through online verification and start selling through our service.`,
//     `Rent out your hotel room on your terms with Your Price Booking | ${city}. Receive payment before moving in, and our commission is only 5%. Manage prices at your discretion and offer customized offers for each client. You have the opportunity to see all users interested in your available numbers and make promotional offers. Travelers know that we offer hoteliers minimal commissions and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your hotel right now, go through online verification and start attracting new clients.`,
//     `Optimize your business with Your Price Booking - a service for booking hotels of all types and daily rental housing. With us, you rent out rooms on your terms, see all the users who are eligible for your offers, and offer individual, confidential prices. Hoteliers pay only 5% commission on each transaction and can change prices at their discretion. There is no price parity - only flexibility and transparency. Register now, go through online verification and attract new clients.`,
//     `Rent your house daily | ${city}, ${country}. On better terms with Your Price Booking. Get paid before you move in, our commission is only 5%. You have complete control over prices and you can make individual offers confidentially. See all users interested in your rental and create promotional offers as much as you want and for free. Travelers know that we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your house, villa or chalet right now. Get verified online and start attracting new customers. Registration will take only 2 minutes.`,
//     `Rent out apartments for daily rent in ${city}, ${country} on your terms with Your Price Booking. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your apartment now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
//     `Rent out your apartment for daily rent in the ${city} location, on your terms with Your Price Booking. Receive payment before moving in and our commission is only 5%. You have complete control over prices and can offer customized quotes in confidence. See all users interested in your rental and create promotional offers. Travelers know we offer minimal commissions to hotels and expect great prices from you. We do not have the principle of price parity, only flexibility and transparency. Register your apartment right now, go through online verification, and start attracting new clients. Registration will only take 2 minutes.`,
//   ],
// };
