const pageCatalog = {
  ru: [
    "sdat-posutochno-zhile",
    "sdat-nomer-v-motele",
    "sdat-nomer-v-capsule-hotel",
    "sdat-nomer-v-guest-house",
    "sdat-komnatu-v-dome-posutochno",
    "sdat-komnatu-v-kvartire-posutochno",
    "sdat-mesto-v-hostele",
    "sdat-nomer-v-otele",
    "sdat-nomer-v-gostinitse",
    "sdat-dom-posutochno",
    "sdat-apartamenty-posutochno",
    "sdat-kvartiru-posutochno",
  ],
  uk: [
    "zdati-zhitlo-dobovo",
    "zdati-nomer-u-moteli",
    "zdati-nomer-v-capsule-hotel",
    "zdati-nomer-v-guest-house",
    "zdati-kimnatu-v-budinku-dobovo",
    "zdati-kimnatu-dobovo",
    "zdati-mistse-u-hosteli",
    "zdati-nomer-u-goteli",
    "zdati-nomer-v-goteli-vsih-tipiv",
    "zdati-budinok-dobovo",
    "zdati-apartamenti-dobovo",
    "zdati-kvartiru-dobovo",
  ],
  en: [
    "rent-out-housing-daily",
    "rent-a-motel-room",
    "rent-a-room-in-capsule-hotel",
    "rent-a-room-in-guest-house",
    "rent-a-room-in-a-house-daily",
    "rent-a-room-in-a-flat-daily",
    "rent-a-place-in-a-hostel",
    "rent-a-hotel-room-daily",
    "rent-a-hotel-room-in-hotel-of-all-types",
    "rent-a-house-daily",
    "rent-an-apartment-daily",
    "rent-a-flat-daily",
  ],
  pl: [
    "wynajme-mieszkanie",
    "wynajme-pokoj-w-motelu",
    "wynajme-pokoj-w-hotelu-kapsulowym",
    "wynajme-pokoj-w-domu-gosccinnym",
    "wynajme-pokoj-w-domu",
    "wynajme-pokoj-w-mieszkaniu",
    "wynajme-miejsce-w-hostelu",
    "wynajmij-pokoj-w-hotelu",
    "wynajac-w-hotelach-wszystkich-typow",
    "wynajac-dom",
    "wynajem-mieszkan-do-wynajecia",
    "wynajac-mieszkanie",
  ],
};

module.exports = pageCatalog;
